version: "3"
services:
  postgres:
    image: 'postgres:9.6'
    container_name: postgres
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
  rails:
    container_name: stackforum_rails
    build: .
    links:
      - postgres
      - sphinx
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  sphinx:
    container_name: stackforum_sphinx
    build:
      context: .
      dockerfile: Dockerfile_sphinx
    links:
      - postgres
    depends_on:
      - postgres